### ISSUE TITLE
Information on Nucleo Yoke

### ISSUE THREAD

**Issue by filipre** [mslawicz/NucleoYokeFF#1]
Hi, 
I am currently looking into different FFB options for flight simulation. I tried to search for "Nucleo Yoke" but I couldn't find anything related to it. Can you provide some information on that product or hardware?
Best
René

**Comment by mslawicz** [comment]
Hi Rene,Nucleo Yoke is my private project to design and check some ideas. A kind of proof of concept. The code is in my Github repositories, but the hardware is a prototype only and not the subject to use by other people. So if you are an electronic desiner and programmer, you can do something similar. Otherwise you have to look somhere else for ready-to-use products.I have already tested these 2 scenarios for FF yoke working with X-Plane:STM32 Nucleo board / yoke input from IMU sensor / electromagnets + neodimium magnets for FF, USB link, self-made plugin in X-Plane 11STM32 Nucleo board / yoke input from tensometer sensors / servos for FF, USB link, self-made plugin in X-Plane 11Both conceptions worked pretty well, but could be troublesome for a casual user. Regards,Marcin  Od: René FilipWysłano: piątek, 7 lutego 2020 09:51Do: mslawicz/NucleoYokeFFDW: SubscribedTemat: [mslawicz/NucleoYokeFF] Information on Nucleo Yoke (#1) Hi,I am currently looking into different FFB options for flight simulation. I tried to search for "Nucleo Yoke" but I couldn't find anything related to it. Can you provide some information on that product or hardware?BestRené—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by filipre** [comment]
I see, thanks! I was actually thinking about building my own FFB yoke mechanics which lead me to this project during my research. If you plan to release more information on your project (blog post, video, etc.) I'd love to see it as well :) In any case, I think looking into your code is already super helpful for me. Keep up the good work!
